<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ReviewAgent.Worker-8e0be310-9bca-4fcd-89a3-6e209ae125fe</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.24" />
    <PackageReference Include="Hangfire.Core" Version="1.8.24" />
    <PackageReference Include="Hangfire.Mongo" Version="1.16.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReviewAgent.Connectors\ReviewAgent.Connectors.csproj" />
    <ProjectReference Include="..\ReviewAgent.AI\ReviewAgent.AI.csproj" />
    <ProjectReference Include="..\ReviewAgent.Data\ReviewAgent.Data.csproj" />
    <ProjectReference Include="..\ReviewAgent.Slack\ReviewAgent.Slack.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\ReviewAgent.Connectors\MockData\reviews_appstore.json" Link="MockData\reviews_appstore.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\ReviewAgent.Connectors\MockData\reviews_googleplay.json" Link="MockData\reviews_googleplay.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\ReviewAgent.Connectors\MockData\reviews_live_demo.json" Link="MockData\reviews_live_demo.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
